#!/usr/bin/env bash

set -e

if [ -z ${VIRTUAL_ENV+x} ]
then
  ACTIVATE_SCRIPT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.env/bin/activate"
  if [ -f "$ACTIVATE_SCRIPT" ]
  then
    # shellcheck source=/dev/null
    source "$ACTIVATE_SCRIPT"
  else
    echo "$ACTIVATE_SCRIPT not found.  Did you follow documentation to install dependencies?"
    exit 1
  fi
fi

# If "psec -E run --" is used it exports a variable we can use
# to switch to a psec specific playbook
if [ -n '${PYTHON_SECRETS_ENVIRONMENT}' ]; then
     PLAYBOOK=main-psec.yml;
else
     PLAYBOOK=main.yml;
fi

case "$1" in
  update-users) PLAYBOOK=users.yml; ARGS=( "${@:2}"  -t update-users ) ;;
  *) ARGS=( "${@}" ) ;;
esac

ansible-playbook ${PLAYBOOK} "${ARGS[@]}"
